// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyGtXfhOYn-MXupAxo97PquJ2jpPYGwn4',
    appId: '1:561638590203:web:7f72a4f270b79eeee6125e',
    messagingSenderId: '561638590203',
    projectId: 'notes-90489',
    authDomain: 'notes-90489.firebaseapp.com',
    storageBucket: 'notes-90489.firebasestorage.app',
    measurementId: 'G-2S1FQTYWYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHOrNYQ4YwtBqRQ46vJDud8ECzawhoYg',
    appId: '1:561638590203:android:1e8581daf98fd5afe6125e',
    messagingSenderId: '561638590203',
    projectId: 'notes-90489',
    storageBucket: 'notes-90489.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyGtXfhOYn-MXupAxo97PquJ2jpPYGwn4',
    appId: '1:561638590203:web:17599bdcaea62a8be6125e',
    messagingSenderId: '561638590203',
    projectId: 'notes-90489',
    authDomain: 'notes-90489.firebaseapp.com',
    storageBucket: 'notes-90489.firebasestorage.app',
    measurementId: 'G-QH9FQ66CX7',
  );

}